### PR TITLE
Bug 2032926: feat: library-go bump and leader election config

### PR DESCRIPTION
**Pull request by eggfoobar**
Bumping the library-go dependency to latest, this should take advantage of leader election changes for SNO clusters proposed in this [library-go PR](https://github.com/openshift/library-go/pull/1242) and performance improvements in this [PR](https://github.com/openshift/library-go/pull/1235).

Changes:
  - updated to latest library-go
  - updated start commands to use leaderelection configs from library-go
  - updated controller-runtime to k8s 0.23.0 support
  - fixed test for new logr interface

Signed-off-by: ehila <ehila@redhat.com>

### CODE REVIEW

**Comment by Fedosin** [comment]
Currently blocked by https://github.com/openshift/release/pull/24668

**Comment by damdo** [comment]
Unit tests are broken also on master, there is a fix https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/159 for them but this one will need to wait until that is merged. cc. @eggfoobar

**Comment by damdo** [comment]
Depends on https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/154

**Comment by Fedosin** [comment]
/retitle Bug 2032926: feat: library-go bump and leader election config

**Review by Fedosin — APPROVED** [review]
/lgtm

**Comment by damdo** [comment]
/lgtm
Great team work! Thanks all @eggfoobar @Fedosin @JoelSpeed

**Pull request merged**
