### PR TITLE
Add label in Dockerfile to include operator in CI release images

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
`@cluster-bot launch 4.7.0-fc.3,openshift/cluster-cloud-controller-manager-operator#7 aws` should give desired operator in a cluster.

### CODE REVIEW

**Review by Fedosin — APPROVED** [review]
/lgtm
/approve
/hold

**Comment by Danil-Grigorev** [comment]
/hold cancel
Confirm cluster running operator and managing clusterOperator status conditions.

**Comment by wking** [comment]
Broke the world.  Reverting in #14.

**Pull request merged**
