### PR TITLE
Rename CCCMO deployment

### PR DESCRIPTION
**Pull request by Fedosin**
This PR sets CCCMO deployment name to cluster-cloud-controller-manager-operator.

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
i think this is a nice change, thanks Mike
/lgtm

are there any other components that still expect the original name? (installer, mco)

**Comment by Fedosin** [comment]
@elmiko fortunately all other components don't rely on this name, so it can be safely changed.

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-upgrade 

This is going to cause no issue for production users as we don't have this component in nightly builds yet. Once this is merged the upgrade job will use a newer image and we should have no further issues

**Comment by Danil-Grigorev** [comment]
/hold 

@Fedosin This PR will break periodics for 4.7->4.8 if merged as is. Please add tombstone object to remove old deployment before rename.

**Pull request merged**
