### PR TITLE
OCPVE-660: add CloudController capability annotation

### PR DESCRIPTION
**Pull request by qJkee**

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
generally looks ok to me
/lgtm

**Comment by elmiko** [comment]
just noticed the images job, want to make sure that is passing

/lgtm cancel
/test images

**Review by JoelSpeed — COMMENTED** [review]
Can you remind me the effect of the `+` syntax in capabilities? IIUC there is no or syntax right?

**Review by elmiko — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
