### PR TITLE
OCPBUGS-21129: Bump golang.org/x/net to v0.18.0

### PR DESCRIPTION
**Pull request by racheljpg**
This is a PR to bump the golang.org/x/net dependency to v0.18.0.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
One of the dependency updates here required a new go version, given this is a 4.11 backport, I think we probably don't want to bump it 2 go versions, so I'm tempted to say this should be a wont fix

**Comment by racheljpg** [comment]
Closing this as the ticket has been closed with "won't fix". Thanks!

**Pull request closed without merging**
