### PR TITLE
Bug 2059716: Ensure release version is set on config sync controller

### PR DESCRIPTION
**Pull request by JoelSpeed**
Follow up to #175, I missed this controller and only added the release version to one of the two controllers in this manager

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by wking** [comment]
openshift/release#26744 should have fixed the `The bootstrap machine failed to download the release image` on build02 jobs.

/retest

**Comment by wking** [comment]
[e2e-azure-upgrade][1] failed on `46 failures to create the sandbox`, but the issue we're trying to fix here looks fixed, with some initial-version flapping clearing up once the target-version comes into the mix:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-cloud-controller-manager-operator/176/pull-ci-openshift-cluster-cloud-controller-manager-operator-master-e2e-azure-upgrade/1499615350587658240/artifacts/e2e-azure-upgrade/openshift-e2e-test/build-log.txt | grep clusteroperator/cloud-controller-manager | tail -n5
Mar 04 06:17:55.460 I clusteroperator/cloud-controller-manager versions: operator 4.11.0-0.ci.test-2022-03-04-051909-ci-op-gdjqfjpj-initial -> 
Mar 04 06:17:55.472 I clusteroperator/cloud-controller-manager versions: operator  -> 4.11.0-0.ci.test-2022-03-04-051909-ci-op-gdjqfjpj-initial
Mar 04 06:18:45.426 I clusteroperator/cloud-controller-manager versions: operator 4.11.0-0.ci.test-2022-03-04-051909-ci-op-gdjqfjpj-initial -> 
Mar 04 06:18:45.440 I clusteroperator/cloud-controller-manager versions: operator  -> 4.11.0-0.ci.test-2022-03-04-051909-ci-op-gdjqfjpj-initial
Mar 04 06:22:18.886 I clusteroperator/cloud-controller-manager versions: operator 4.11.0-0.ci.test-2022-03-04-051909-ci-op-gdjqfjpj-initial -> 4.11.0-0.ci.test-2022-03-04-052257-ci-op-gdjqfjpj-latest
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-cloud-controller-manager-operator/176/pull-ci-openshift-cluster-cloud-controller-manager-operator-master-e2e-azure-upgrade/1499615350587658240

**Pull request merged**
