### PR TITLE
Add support for IBM images

### PR DESCRIPTION
**Pull request by rtheis**

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
this generally looks good to me, need to review it again in comparison to our other providers.

**Comment by JoelSpeed** [comment]
Changes look good, will need to keep the hold until the IBM provider image is added to the release payload though

**Review by elmiko — COMMENTED** [review]
thanks Richard
/approve

**Comment by rtheis** [comment]
PR has been rebased.

**Comment by JoelSpeed** [comment]
IBM images should be in the next nightly
/retest-required

**Comment by JoelSpeed** [comment]
/hold cancel
/lgtm

IBM images should be in the nightlies now

**Pull request merged**
