### PR TITLE
OCPBUGS-29012: Increase Azure Concurrent Service Syncs to 10

### PR DESCRIPTION
**Pull request by JoelSpeed**
This should increase the reactiveness of the Azure service controller, meaning that creation and deletion of load balancers is quicker.

/hold

I would like to review the service controller implementation within Azure and run payload testing before we merge this

### CODE REVIEW

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-azure-sdn-upgrade

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/approve
Based on conversation between myself and @elmiko we are going to move forward with increasing the concurrency of the Azure cloud provider, discussion noted in the bug linked

**Pull request merged**
