### PR TITLE
OCPBUGS-15746: Alibaba platforms should not be upgradeable

### PR DESCRIPTION
**Pull request by JoelSpeed**
Manual cherry-pick of #257

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-alibaba-ovn

**Comment by elmiko** [comment]
the vet failure looks like maybe there is another reference to `setStatusAvailable` that needs updating

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
