### PR TITLE
trt-1382: reorder flag initialization

### PR DESCRIPTION
**Pull request by neisw**
Based on https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/307#issuecomment-1849114982

### CODE REVIEW

**Comment by neisw** [comment]
/hold

Seems that there was an unintentional update to go 1.21 for 4.16 that is being reverted

**Comment by stbenjam** [comment]
I'd suggest merging this anyway to be ready for go 1.21, https://github.com/google/cadvisor/pull/3384 indicates this is a known problem for 1.21

**Comment by neisw** [comment]
Thank you @thegreyd for finding https://github.com/google/cadvisor/pull/3384

/hold cancel
/retest-required

**Pull request merged**
