### PR TITLE
Fix container names in azure manifests

### PR DESCRIPTION
**Pull request by lobziik**

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
thanks Denis
/approve

**Review by Fedosin — APPROVED** [review]
/lgtm

**Comment by Fedosin** [comment]
Do we plan to update other platforms accordingly? 
AWS: https://github.com/openshift/cluster-cloud-controller-manager-operator/blob/master/pkg/cloud/aws/assets/deployment.yaml#L38
OpenStack: https://github.com/openshift/cluster-cloud-controller-manager-operator/blob/master/pkg/cloud/openstack/assets/deployment.yaml#L45

**Comment by lobziik** [comment]
@Fedosin No. https://github.com/openshift/cluster-cloud-controller-manager-operator/blob/master/pkg/substitution/substitution.go#L17 Needed for azure only

**Pull request merged**
