### PR TITLE
Bug 2067806: Bump dependencies to K8s 1.24

### PR DESCRIPTION
**Pull request by JoelSpeed**
To prepare for the Kubernetes 1.24 release, we should make sure our dependencies are up to date. This bumps all of the kube related dependencies to v0.24.0 and then also bumps Go to 1.18

### CODE REVIEW

**Comment by lobziik** [comment]
Vendor step needs to be fixed in openshit/release repo by bumping go version.
/approve
/hold

**Review by elmiko — COMMENTED** [review]
/lgtm

**Pull request merged**
