### PR TITLE
OCPBUGS-23996: trust bundle CA controller: add owner annotation for ccm-trusted-ca configmap

### PR DESCRIPTION
**Pull request by vrutkovs**
This adds annotation which identifies the component used to file issues with this certificate. The annotation is verified by [the test](https://github.com/openshift/origin/blob/master/test/extended/operators/certs.go#L130), so that all certificates would be registered and have owners assigned. More metadata would be added later.

See https://github.com/openshift/enhancements/pull/1502 for proposed workflow with TLS registry

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@vrutkovs Can you add a PR description that explains why this is happening. I have no idea what this annotation is

**Comment by vrutkovs** [comment]
Done

**Pull request merged**
