### PR TITLE
[OCPCLOUD-1988] Update library-go dependency to move AWS to out of tree

### PR DESCRIPTION
**Pull request by JoelSpeed**
This PR updates the library-go dependency to include [a bump to move the AWS cloud provider to out-of-tree](https://github.com/openshift/library-go/pull/1485). Note this PR must be merged at the same time as a [PR to KCMO](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/707) making the same bump to avoid a build that contains only one of the two bumps.

Tested with [Cluster Bot](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1633075931457261568)

### CODE REVIEW

**Comment by JoelSpeed** [comment]
CI results looked good for the original commit (linked in PR description) but a unit test failed, pushed a second commit for the unit test fix, assuming that's good, since it doesn't affect the product, I think this is good to go still.
Presubmit tests won't pass because we need the KCMO PR as well for those to pass

**Comment by JoelSpeed** [comment]
Unit tests passed this time, except from some render benchmarks, IMO, the benchmarks aren't important here as we've been seeing them flake a lot, hazard of running tests in a container, I'm not going to block this PR on them and will get someone to investigate improving this signal in the future
/override ci/prow/unit

**Comment by deads2k** [comment]
as in prior runs, a payload containing all the changes will bootstrap and upgrade successfully.  The manual verification across PRs is green.  I'm button merging these to ensure we don't get a payload that is missing some of the changes.

**Pull request merged**
