### PR TITLE
OCPBUGS-1411: Bump dependencies to k8s 1.25

### PR DESCRIPTION
**Pull request by lobziik**
Update dependencies, bump envtest version

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/lgtm
/approve
/retest-required

**Comment by lobziik** [comment]
Updated this pr:
Cherry-picked #204, updated comments formatting to align `go fmt` 1.19.
Also vendored setup-envtest, golangci-lint and controller-gen

**Pull request merged**
