### PR TITLE
[release-4.9] Bug 2015503: User CA bundle sync controller

### PR DESCRIPTION
**Pull request by lobziik**
Manual cherry-pick of https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/136

Needed for enable installation of OpenShift on Azure Stack with custom CA.

Related installer bug: https://bugzilla.redhat.com/show_bug.cgi?id=2010921

### CODE REVIEW

**Comment by lobziik** [comment]
I cherry picked commits from https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/140 additionally.

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by mgahagan73** [comment]
/lgtm

I have tested and confirmed this is working in our ASH environment

**Pull request merged**
