### PR TITLE
Enable cloud-config-sync controller

### PR DESCRIPTION
**Pull request by lobziik**
Enable missed cloud-config-sync controller. Forgot to include in in final version of #61. Sorry...

### CODE REVIEW

**Comment by lobziik** [comment]
cc @Danil-Grigorev @JoelSpeed

**Review by Danil-Grigorev — APPROVED** [review]
/lgtm

**Review by Danil-Grigorev — APPROVED** [review]
/lgtm

**Review by elmiko — APPROVED** [review]
/lgtm

**Pull request merged**
