### PR TITLE
Add etcd fetcher for CI task

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Bring fetching scripts from controller-runtime to allow test job from https://github.com/openshift/release/pull/14749 to pass.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Comment by Danil-Grigorev** [comment]
self /approve ?

**Review by Fedosin — APPROVED** [review]
/lgtm
/approve

**Comment by Danil-Grigorev** [comment]
Attempting to close the PR and reopen it in order to trigger CI runs on it.

/reopen

**Pull request merged**
