### PR TITLE
Bug 2004924: Enforce the cloud-route controller disabled across platforms

### PR DESCRIPTION
**Pull request by JoelSpeed**
Manual cherry-pick of #120 

We must disable the route controller across platforms as it is not supported within OpenShift.

### CODE REVIEW

**Review by Fedosin — COMMENTED** [review]
/lgtm
/approve

**Comment by hardys** [comment]
Discussed and agreed blocker status, adding staff-eng-approved

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-openstack-ccm

Have discussed this with @pierreprinetti and @mdbooth on slack. This job is currently perma-failing due to a ci-config issue and as such will never pass. It was also accidentally marked as required. We are moving the job back to optional until we are confident in its stability

**Pull request merged**
