### PR TITLE
Minimize IAM scope for IBM Cloud CredReqs

### PR DESCRIPTION
**Pull request by cjschaef**
Minimize the IAM scope for the IBM Cloud CCM, based on required
resources and permissions.

### CODE REVIEW

**Comment by cjschaef** [comment]
Need some confirmation from IBM network team on which roles are applicable and verify there are no additional services that need permissions.

**Review by elmiko — COMMENTED** [review]
this makes sense, although i am no expert on the ibm policy permissions. would like to get an additional review on this.
/approve

**Review by rtheis — APPROVED** [review]
/lgtm

**Comment by shalver** [comment]
/lgtm
but honestly this is not something I am very familiar with

**Pull request merged**
