### PR TITLE
OCPCLOUD-2010: Re-vendor api and library-go for external platform support

### PR DESCRIPTION
**Pull request by adriengentil**
Revendor openshift/api and openshift/library-go in order to support the
external platform type.

library-go PR: openshift/library-go#1496
API PR: openshift/api#1434

### CODE REVIEW

**Comment by adriengentil** [comment]
Pinned `k8s/api` to `0.26.1` due to the incompatibility with `sigs.k8s.io/controller-runtime` version `0.14.*`

Updating to `sigs.k8s.io/controller-runtime` to `v0.15.0-beta.0`, which would solve the issue, leads to compilation errors:
```
$ make build
go build -o bin/cluster-controller-manager-operator cmd/cluster-cloud-controller-manager-operator/main.go
# github.com/openshift/cluster-cloud-controller-manager-operator/pkg/restmapper
pkg/restmapper/restmapper.go:23:12: undefined: apiutil.WithLazyDiscovery
pkg/restmapper/restmapper.go:24:12: undefined: apiutil.WithCustomMapper
# github.com/openshift/cluster-cloud-controller-manager-operator/pkg/controllers
pkg/controllers/cache.go:85:36: cannot use &eventToChannelHandler{…} (value of type *eventToChannelHandler) as "k8s.io/client-go/tools/cache".ResourceEventHandler value in argument to informer.AddEventHandler: *eventToChannelHandler does not implement "k8s.io/client-go/tools/cache".ResourceEventHandler (wrong type for method OnAdd)
		have OnAdd(interface{})
		want OnAdd(interface{}, bool)
pkg/controllers/cloud_config_sync_controller.go:265:5: source.Kind (value of type func(cache "sigs.k8s.io/controller-runtime/pkg/cache".Cache, object client.Object) source.SyncingSource) is not a type
pkg/controllers/cloud_config_sync_controller.go:266:39: cannot use toManagedConfigMap (value of type func(client.Object) []reconcile.Request) as handler.MapFunc value in argument to handler.EnqueueRequestsFromMapFunc
pkg/controllers/cloud_config_sync_controller.go:270:5: source.Kind (value of type func(cache "sigs.k8s.io/controller-runtime/pkg/cache".Cache, object client.Object) source.SyncingSource) is not a type
pkg/controllers/cloud_config_sync_controller.go:271:39: cannot use toManagedConfigMap (value of type func(client.Object) []reconcile.Request) as handler.MapFunc value in argument to handler.EnqueueRequestsFromMapFunc
pkg/controllers/clusteroperator_controller.go:192:12: source.Kind (value of type func(cache "sigs.k8s.io/controller-runtime/pkg/cache".Cache, object client.Object) source.SyncingSource) is not a type
pkg/controllers/clusteroperator_controller.go:193:39: cannot use toClusterOperator (value of type func(client.Object) []reconcile.Request) as handler.MapFunc value in argument to handler.EnqueueRequestsFromMapFunc
pkg/controllers/clusteroperator_controller.go:195:12: source.Kind (value of type func(cache "sigs.k8s.io/controller-runtime/pkg/cache".Cache, object client.Object) source.SyncingSource) is not a type
pkg/controllers/clusteroperator_controller.go:196:39: cannot use toClusterOperator (value of type func(client.Object) []reconcile.Request) as handler.MapFunc value in argument to handler.EnqueueRequestsFromMapFunc
pkg/controllers/clusteroperator_controller.go:198:12: source.Kind (value of type func(cache "sigs.k8s.io/controller-runtime/pkg/cache".Cache, object client.Object) source.SyncingSource) is not a type
pkg/controllers/clusteroperator_controller.go:198:12: too many errors
make: *** [Makefile:43: operator] Error 1

```

**Comment by elmiko** [comment]
/lgtm

let's see how the e2e tests turn out to make sure we aren't breaking anything

**Comment by elmiko** [comment]
in two of the cases it looks like there is some csi driver related issue, and the other case is about a failed node. i don't think these are related to this change.

/lgtm

**Pull request merged**
